import type { Metadata } from "next";
import "./globals.css";
import AppNavbar from "./components/AppNavbar";
import AppFooter from "./components/AppFooter";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <div className="container-fluid">
          <AppNavbar></AppNavbar>
          <div className="card bg-base-100 shadow-xl flex-1">
            {children}
          </div>
          <AppFooter/>
        </div>
        
        </body>
    </html>
  );
}


// Remove Tailwind and integrate only with Bootstrap
// REST API
// authentication / (middleware)
// internationalization/localization
// E2E integration (Optional CYpress)
// Unit Testing (Optional Jest)



